# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  increment_build_number(
    build_number: app_store_build_number + 1,
    xcodeproj: "MatchScoresTCA.xcodeproj"
  )
end

lane :release do
  build_app(scheme: "MatchScoresTCA")
end

lane :screenshots do
  snapshot 
  frameit(white: true)
  deliver
end

desc "Create ipa"
 lane :build do
   #update profiles
   sync_certificates
   # Increases the build number by 1
   increment_build_number
   # Creates a signed file
   gym
 end
end
